name: tune_stack
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  envied: ^0.5.4+1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^5.0.1
  master_utility: ^0.0.14
  internet_connection_checker: ^1.0.0+1
  import_sorter: ^4.6.0
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  easy_localization: ^3.0.7
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  toastification: ^3.0.2
  pin_code_fields: ^8.0.1
  permission_handler: ^11.4.0
  device_info_plus: ^10.1.2
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  vector_graphics: ^1.1.18
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  firebase_storage: ^12.4.5
  supabase_flutter: ^2.8.4
  intl: ^0.20.2
  just_audio: ^0.9.46
  audio_video_progress_bar: ^2.0.3
  path: ^1.9.0
  mime: ^2.0.0
  video_player: ^2.9.5

dev_dependencies:
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  danger_core: ^2.0.0
  build_runner: ^2.4.9
  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.10.0

dependency_overrides:
  intl:
  watcher: ^1.1.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.production
    - assets/colors/
    - assets/icons/


# flutter_gen:
#   integrations:
#     flutter_svg: true

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Light.ttf
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-Medium.ttf
        - asset: assets/fonts/Heebo-SemiBold.ttf
        - asset: assets/fonts/Heebo-Bold.ttf
        - asset: assets/fonts/Heebo-ExtraBold.ttf



flutter_gen:
  output: lib/config/assets/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true

    exclude:
      - .env
      - .env.development
      - .env.production

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml
  
  
